version: 2
updates:
  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  # Check for updates to NuGet packages every week
  - package-ecosystem: "nuget"
    directories:
    - "/test/WebExtensions.Net.BrowserExtensionIntegrationTest/"
    - "/test/WebExtensions.Net.IntegrationTestsRunner/"
    allow:
    - dependency-type: "direct"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      aspnetcore:
        patterns: [ Microsoft.AspNetCore.* ]
      mstest:
        patterns: [ MSTest.* ]
